'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmCapCobranzaDoc
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FormasPago.frmCapCobranzaDoc", GetType(frmCapCobranzaDoc).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptar_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptar.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptar_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptar.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarCliente_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarCliente.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarCliente_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarCliente.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnCancelar_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCancelar.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnCancelar_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnCancelar.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=138,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property cmListaPedidos_Location() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("cmListaPedidos.Location", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmListaPedidos_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmListaPedidos.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property GroupBox1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupBox1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property GroupBox2_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupBox2.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpDatosCobro_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDatosCobro.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label2_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label2.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label3_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label3.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label4_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label4.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label5_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label5.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label6_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label6.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label7_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label7.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label8_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label8.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblImportePorAplicar_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblImportePorAplicar.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblImporteTotalCobranza_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblImporteTotalCobranza.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblPedidoReferenciaImporte_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPedidoReferenciaImporte.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblTipoCobro_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblTipoCobro.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblTotalCobro_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblTotalCobro.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lstDocumento_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lstDocumento.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property mnuEliminar_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("mnuEliminar.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property ttDatosPedido_Location() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("ttDatosPedido.Location", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property ttDatosPedido_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("ttDatosPedido.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtCliente_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtCliente.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtImporteAbono_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtImporteAbono.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtPedidoReferencia_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtPedidoReferencia.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
End Class
