'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmSelTipoCobro
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FormasPago.frmSelTipoCobro", GetType(frmSelTipoCobro).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarChequeFicha_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarChequeFicha.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarChequeFicha_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarChequeFicha.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarEfectivoVales_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarEfectivoVales.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarEfectivoVales_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarEfectivoVales.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarTarjetaCredito_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarTarjetaCredito.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarTarjetaCredito_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarTarjetaCredito.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarCliente_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarCliente.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarCliente_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarCliente.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarClienteTC_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarClienteTC.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarClienteTC_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarClienteTC.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property ComboBanco_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("ComboBanco.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property dtpFechaCheque_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("dtpFechaCheque.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpChequeFicha_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpChequeFicha.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpEfectivoVales_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpEfectivoVales.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpTarjetaCredito_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpTarjetaCredito.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property imgLista_Location() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLista.Location", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property imgLista_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLista.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label20_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label20.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Label21_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Label21.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase2_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase2.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase3_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase3.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase4_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase4.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase5_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase5.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase6_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase6.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property LabelBase7_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("LabelBase7.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblBanco_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblBanco.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblBancoNombre_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblBancoNombre.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCliente_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCliente.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblClienteNombre_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblClienteNombre.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblFechaCheque_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblFechaCheque.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblImporte_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblImporte.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblNoCheque_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblNoCheque.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblNoCuenta_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblNoCuenta.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblNombre_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblNombre.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblObservaciones_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblObservaciones.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblTarjetaCredito_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblTarjetaCredito.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblTipoTarjetaCredito_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblTipoTarjetaCredito.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblTitular_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblTitular.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblTotalEfectivoVales_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblTotalEfectivoVales.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblVigencia_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblVigencia.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property rbCheque_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("rbCheque.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property rbFicha_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("rbFicha.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property rbNotaCredito_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("rbNotaCredito.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property tabTipoCobro_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("tabTipoCobro.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property tbChequeFicha_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("tbChequeFicha.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property tbEfectivoVales_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("tbEfectivoVales.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property tbTarjetaCredito_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("tbTarjetaCredito.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtClienteCheque_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtClienteCheque.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtClienteTC_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtClienteTC.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtDocumento_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtDocumento.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtImporteDocumento_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtImporteDocumento.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtImporteTC_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtImporteTC.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtNumeroCuenta_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtNumeroCuenta.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtObservaciones_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtObservaciones.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.CodeDom.MemberAttributes similar a Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtTotalEfectivoVales_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtTotalEfectivoVales.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
End Class
