'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmSelTipoCobroPortatil
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FormasPago.frmSelTipoCobroPortatil", GetType(frmSelTipoCobroPortatil).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Boolean similar a True.
    '''</summary>
    Friend Shared ReadOnly Property año_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("año.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BotonBase2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BotonBase2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BotonBase3_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BotonBase3.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BotonBuscarClienteApAnticipo_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BotonBuscarClienteApAnticipo.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_AnticipoAceptar_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_AnticipoAceptar.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarChequeFicha_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarChequeFicha.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnAceptarTarjetaCredito_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnAceptarTarjetaCredito.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarCliente_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarCliente.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnBuscarClienteTC_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnBuscarClienteTC.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BtnBuscarClienteVales_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BtnBuscarClienteVales.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Button1_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Button1.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Button2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Button2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Boolean similar a True.
    '''</summary>
    Friend Shared ReadOnly Property folio_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("folio.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property imgLista_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLista.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Boolean similar a True.
    '''</summary>
    Friend Shared ReadOnly Property MontoSaldo_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("MontoSaldo.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
End Class
